"$schema" = "./node_modules/wrangler/config-schema.json"
name = "tactus-website"
pages_build_output_dir = ".cloudflare/pages"
compatibility_date = "2026-02-14"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "tactus-skills"
database_id = "82987a5a-6344-4fd0-8bf6-8e4482096887"

[[r2_buckets]]
binding = "SKILLS_BUCKET"
bucket_name = "tactus-skills"
